# For most projects, this workflow file will not need changing; you simply need
# to commit it to your repository.
#
# You may wish to alter this file to override the set of languages analyzed,
# or to provide custom queries or build logic.
#
# ******** NOTE ********
# We have attempted to detect the languages in your repository. Please check
# the `language` matrix defined below to confirm you have the correct set of
# supported CodeQL languages.

name: "Xygeni Action - Test"

on:
  #push:
  #  branches: [ "main" ]
  #pull_request:
    # The branches below must be a subset of the branches above
  #  branches: [ "main" ]
  #schedule:
  #  - cron: '44 16 * * 0'
  workflow_dispatch:

jobs:
  analyze:
    name: Analyze
    runs-on: ${{ (matrix.language == 'swift' && 'macos-latest') || 'ubuntu-latest' }}
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'java' ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Xygeni-Scanner-LabDev
      uses: xygeni/xygeni-action@4e94e5ea737f5ebfedac8b1a5b75d8c60c21932d
      id: Xygeni-Scanner
      with:
        command: scan --never-fail -e '**/test/**,**/target/**,**/docs/node_modules/**,**/doc/**' -o ./test.sarif -f sarif --send-to=github
        token: ${{ secrets.XYGENI_TOKEN }}
        gh_token: ${{ secrets.GH_PAT_FOR_DOGFOODING }}
        xygeni_url: https://apidev.xygeni.io/deps-doctor-service
    #- name: Upload SARIF file
    #  uses: github/codeql-action/upload-sarif@v2
    #  with:
          # Path to SARIF file relative to the root of the repository
    #    sarif_file: results.sarif
          # Optional category for the results
          # Used to differentiate multiple results for one commit
    #    category: my-analysis-tool
